#!/usr/bin/bash

echo
echo mpv add more information to commit message:

branchPath=$(git symbolic-ref -q HEAD) #Somthing like refs/heads/myBranchName
branchName=${branchPath##*/}      #Get text behind the last / of the branch path
user=$USER
hostname=$(hostname)
unamestr=$(uname)
os_type=$OSTYPE

in_docker=false
if [ -f /.dockerenv ]; then
    in_docker=true
fi

echo commit file: $1
echo branchPath: $branchPath
echo branchName: $branchName
echo user: $user 
echo hostname: $hostname
echo in_docker: $in_docker


echo >> $1
echo Information added by mpv: >> $1
echo ------------------------: >> $1
echo branch: $branchName >> $1
echo mpv_version: $mpv_version >> $1
echo user: $user >> $1
echo hostname: $hostname >> $1
echo in_docker: $in_docker >> $1
echo unamestr: $unamestr >> $1
echo os_type: $os_type >> $1
